version: "3"
services:
  app:
    restart: always
    build: .
    ports:
      - "3000:8080"
    links:
      - mongo
    networks:
      - my-network
    volumes:
      - ./api:/usr/src/app/api
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - my-network
networks:
  my-network:
    driver: bridge
