name: hadolint testing
on: [push]

jobs:                                                                                            
  test-hado:                                                                                         
    name: deploy                                                                     
    runs-on: ubuntu-latest                                                                       
    steps:
      - name: copy source application
        uses: actions/checkout@v2
      - name: install docker  
        run: curl -sSL https://get.docker.com | sh
      - name: install hadolint from docker 
        run: docker run --rm -i hadolint/hadolint < Dockerfile
